#import <Foundation/Foundation.h>
#import <Capacitor/Capacitor.h>

// Generated by @aparajita/capacitor-native-decorator/make-ios-plugin

CAP_PLUGIN(DarkMode, "DarkMode",
  CAP_PLUGIN_METHOD(isDarkMode, CAPPluginReturnPromise);
  CAP_PLUGIN_METHOD(setNativeDarkModeListener, CAPPluginReturnCallback);
)
